version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: job-match
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - service-network
    volumes:
      - /opt:/opt
      
  nginx:
    container_name: load-balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt:/opt:ro
    depends_on:
      - app
    ports:
      - "8090:8090"
    networks:
      - service-network
networks:
  service-network:
    external: true
    name: jobmatch_network