version: "3"
services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql_test
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1
    networks:
      - db-network

  phpmyadmin:
    depends_on:
      - mysql-server
    image: phpmyadmin
    container_name: phpMyAdmin_test
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mysql
    networks:
      - db-network

  redis:
    image: redis:7.2.3
    restart: unless-stopped
    container_name: redis_test
    ports:
      - "6379:6379"
    volumes:
      - '/path/to/redis-persistence:/bitnami'
    networks:
      - db-network

networks:
  db-network:
    external: true
    driver: bridge
    name: jobmatch_network